import type { ServiceCategory, ServiceItem, ServiceStatus } from './serviceCatalogTypes'

export type { ServiceCategory, ServiceItem, ServiceStatus }

import type { VerificationBadge } from './serviceCatalogTypes'

const PROVIDER_RAKESH = {
  title: 'Certified Farm Advisor',
  experienceYears: 8,
  responseTime: '2 hours',
  responseRate: 98,
  acceptanceRate: 95,
  specializations: ['Organic farming', 'Soil health', 'Crop rotation', 'Pest management'],
  certifications: ['Indian Organic Certification', 'CropVibe Verified Expert'],
  verifications: ['identity', 'email', 'phone', 'tax', 'expert'] as VerificationBadge[],
  serviceAreas: ['Pune', 'Ahmednagar', 'Satara'],
  repeatCustomers: 18,
  verifiedBookings: 24,
  onTimeRate: 98,
}

const PROVIDER_PRIYA = {
  title: 'Soil Scientist & Advisor',
  experienceYears: 6,
  responseTime: '4 hours',
  responseRate: 96,
  acceptanceRate: 92,
  specializations: ['Soil health', 'Lab analysis', 'Nutrient planning'],
  certifications: ['ICAR Certified', 'CropVibe Verified Expert'],
  verifications: ['identity', 'email', 'phone', 'expert'] as VerificationBadge[],
  serviceAreas: ['Nashik', 'Pune'],
  repeatCustomers: 12,
  verifiedBookings: 18,
  onTimeRate: 97,
}

export const SERVICE_CATALOG: Record<ServiceCategory, ServiceItem[]> = {
  consultancy: [
    {
      id: 'S-101',
      title: 'Farm Consultancy',
      subtitle: 'Crop planning guidance',
      provider: 'Rakesh Kumar',
      rate: 2500,
      unit: 'session',
      durationMinutes: 60,
      status: 'open',
      location: 'Pune',
      rating: 4.8,
      reviewCount: 24,
      description:
        'Personalized guidance on crop selection, rotation, and soil preparation for maximum yield. Includes live video consultation and a written follow-up plan.',
      includes: [
        'Live video consultation',
        'Personalized farm analysis',
        'Email summary & recommendations',
        '7-day email support',
      ],
      nextAvailable: ['Aug 30', 'Sep 2', 'Sep 5'],
      createdAt: '2025-06-01',
      bookingCount: 48,
      cancellationPolicy: 'Free cancellation up to 24 hours before the session.',
      format: 'Video call + email follow-up',
      providerProfile: PROVIDER_RAKESH,
      reviews: [
        {
          id: 'rv-1',
          author: 'Suresh Sharma',
          rating: 5,
          text: 'Excellent advice on crop rotation. Rakesh helped me increase yield by 30%. Highly recommend!',
          date: 'Oct 5, 2025',
          verified: true,
        },
        {
          id: 'rv-2',
          author: 'Anita Patil',
          rating: 5,
          text: 'Great guidance on soil health. Very practical and easy to follow.',
          date: 'Sep 18, 2025',
          verified: true,
        },
        {
          id: 'rv-3',
          author: 'Vikram Desai',
          rating: 4,
          text: 'Good session on organic pest management. Would book again.',
          date: 'Aug 22, 2025',
          verified: true,
        },
      ],
    },
    {
      id: 'S-102',
      title: 'Soil Health Advisory',
      subtitle: 'Lab analysis + action plan',
      provider: 'Priya Sharma',
      rate: 4200,
      unit: 'session',
      durationMinutes: 90,
      status: 'booked',
      location: 'Nashik',
      rating: 4.5,
      reviewCount: 18,
      description:
        'Comprehensive soil health review with lab-backed recommendations and a customized nutrient plan for your farm.',
      includes: ['Soil sample review', 'Nutrient plan', 'Follow-up call', 'PDF report'],
      nextAvailable: ['Sep 8', 'Sep 12'],
      createdAt: '2025-05-15',
      bookingCount: 32,
      cancellationPolicy: '50% refund if cancelled within 48 hours.',
      format: 'Video call + lab report review',
      providerProfile: PROVIDER_PRIYA,
      reviews: [
        {
          id: 'rv-4',
          author: 'Ramesh Yadav',
          rating: 5,
          text: 'Detailed soil analysis with clear next steps. Priya is very knowledgeable.',
          date: 'Nov 2, 2025',
          verified: true,
        },
        {
          id: 'rv-5',
          author: 'Kavita More',
          rating: 4,
          text: 'Helpful nutrient plan. Report was thorough.',
          date: 'Oct 12, 2025',
          verified: true,
        },
      ],
    },
    {
      id: 'S-103',
      title: 'Organic Transition Coaching',
      subtitle: 'Certification-ready farm plan',
      provider: 'Rakesh Kumar',
      rate: 8500,
      unit: 'package',
      durationMinutes: 120,
      status: 'open',
      location: 'Pune',
      rating: 4.9,
      reviewCount: 11,
      description:
        'Multi-session coaching to transition your farm to organic practices with certification readiness support.',
      includes: ['3 live sessions', 'Transition roadmap', 'Certification checklist', '30-day chat support'],
      nextAvailable: ['Sep 1', 'Sep 4', 'Sep 9'],
      createdAt: '2025-07-20',
      bookingCount: 15,
      cancellationPolicy: 'Full refund if cancelled 7+ days before first session.',
      format: 'Video calls + shared documents',
      providerProfile: PROVIDER_RAKESH,
      reviews: [
        {
          id: 'rv-6',
          author: 'Deepak Kulkarni',
          rating: 5,
          text: 'Structured program that made organic transition feel achievable.',
          date: 'Dec 1, 2025',
          verified: true,
        },
      ],
    },
  ],
  testing: [
    {
      id: 'T-201',
      title: 'Soil Testing Pack',
      subtitle: 'NPK + moisture analysis',
      provider: 'AgriLab Pune',
      rate: 1800,
      unit: 'sample',
      durationMinutes: 0,
      status: 'open',
      location: 'Ahmednagar',
      rating: 4.6,
      reviewCount: 31,
      description: 'Standard soil nutrient panel with moisture and pH readings.',
      includes: ['Sample pickup', 'Lab report', 'Recommendations'],
      nextAvailable: ['Aug 28', 'Aug 29'],
      createdAt: '2025-04-10',
      bookingCount: 89,
      cancellationPolicy: 'Cancel before sample pickup for full refund.',
      format: 'On-site sample collection',
      providerProfile: {
        title: 'Accredited Soil Lab',
        experienceYears: 12,
        responseTime: '1 day',
        responseRate: 99,
        acceptanceRate: 100,
        specializations: ['Soil testing', 'Water testing'],
        certifications: ['NABL Accredited'],
        verifications: ['identity', 'email', 'tax'],
        serviceAreas: ['Pune', 'Ahmednagar'],
        repeatCustomers: 45,
        verifiedBookings: 31,
        onTimeRate: 99,
      },
      reviews: [
        {
          id: 'rv-t1',
          author: 'Farmer, Pune',
          rating: 5,
          text: 'Fast turnaround and clear report.',
          date: 'Jan 10, 2026',
          verified: true,
        },
      ],
    },
    {
      id: 'T-202',
      title: 'Water Quality Check',
      subtitle: 'pH + EC + TDS',
      provider: 'ClearWater Labs',
      rate: 1200,
      unit: 'sample',
      durationMinutes: 0,
      status: 'paused',
      location: 'Satara',
      rating: 4.2,
      reviewCount: 9,
      description: 'Irrigation water quality assessment for safe crop use.',
      includes: ['On-site sample', 'Digital report'],
      nextAvailable: [],
      createdAt: '2025-03-01',
      bookingCount: 22,
      cancellationPolicy: 'Contact support for rescheduling.',
      format: 'Lab analysis',
      providerProfile: {
        title: 'Water Quality Lab',
        experienceYears: 5,
        responseTime: '2 days',
        responseRate: 90,
        acceptanceRate: 88,
        specializations: ['Water testing'],
        certifications: ['ISO 9001'],
        verifications: ['email', 'tax'],
        serviceAreas: ['Satara'],
        repeatCustomers: 4,
        verifiedBookings: 9,
        onTimeRate: 92,
      },
      reviews: [],
    },
  ],
  repair: [
    {
      id: 'R-301',
      title: 'Irrigation Pump Repair',
      subtitle: 'On-site diagnostics',
      provider: 'Kisan Mechanics',
      rate: 3000,
      unit: 'visit',
      durationMinutes: 120,
      status: 'open',
      location: 'Kolhapur',
      rating: 4.7,
      reviewCount: 15,
      description: 'Field visit for pump troubleshooting and repair.',
      includes: ['Diagnosis', 'Parts estimate', 'Same-day fix when possible'],
      nextAvailable: ['Aug 27', 'Aug 31'],
      createdAt: '2025-05-01',
      bookingCount: 41,
      cancellationPolicy: 'Free reschedule up to 12 hours before visit.',
      format: 'On-site visit',
      providerProfile: {
        title: 'Farm Equipment Technician',
        experienceYears: 10,
        responseTime: '6 hours',
        responseRate: 94,
        acceptanceRate: 91,
        specializations: ['Pump repair', 'Irrigation systems'],
        certifications: ['CropVibe Verified'],
        verifications: ['identity', 'phone', 'expert'],
        serviceAreas: ['Kolhapur', 'Satara'],
        repeatCustomers: 9,
        verifiedBookings: 15,
        onTimeRate: 95,
      },
      reviews: [
        {
          id: 'rv-r1',
          author: 'Santosh Jadhav',
          rating: 5,
          text: 'Fixed our pump same day. Professional service.',
          date: 'Feb 2, 2026',
          verified: true,
        },
      ],
    },
    {
      id: 'R-302',
      title: 'Sprayer Maintenance',
      subtitle: 'Annual service',
      provider: 'FarmCare Services',
      rate: 4500,
      unit: 'visit',
      durationMinutes: 90,
      status: 'booked',
      location: 'Pune',
      rating: 4.4,
      reviewCount: 11,
      description: 'Full sprayer calibration and maintenance service.',
      includes: ['Calibration', 'Nozzle check', 'Service report'],
      nextAvailable: ['Sep 3'],
      createdAt: '2025-04-20',
      bookingCount: 28,
      cancellationPolicy: 'Cancel 24h ahead for full refund.',
      format: 'On-site visit',
      providerProfile: {
        title: 'Equipment Service Provider',
        experienceYears: 7,
        responseTime: '1 day',
        responseRate: 92,
        acceptanceRate: 90,
        specializations: ['Sprayer maintenance'],
        certifications: ['Authorized Service Partner'],
        verifications: ['identity', 'email'],
        serviceAreas: ['Pune'],
        repeatCustomers: 6,
        verifiedBookings: 11,
        onTimeRate: 93,
      },
      reviews: [],
    },
  ],
  aerial: [
    {
      id: 'A-401',
      title: 'Drone Spraying Slot',
      subtitle: '5 acre minimum',
      provider: 'SkyFarm Drones',
      rate: 6500,
      unit: 'acre',
      durationMinutes: 180,
      status: 'open',
      location: 'Baramati',
      rating: 4.9,
      reviewCount: 42,
      description: 'Precision drone spraying for pesticides and nutrients.',
      includes: ['Pilot + drone', 'Flight log', 'Coverage map'],
      nextAvailable: ['Aug 29', 'Sep 1'],
      createdAt: '2025-06-15',
      bookingCount: 67,
      cancellationPolicy: 'Weather-related reschedules at no charge.',
      format: 'On-field drone operation',
      providerProfile: {
        title: 'Licensed Drone Operator',
        experienceYears: 4,
        responseTime: '4 hours',
        responseRate: 97,
        acceptanceRate: 96,
        specializations: ['Drone spraying', 'Crop imaging'],
        certifications: ['DGCA Licensed Pilot'],
        verifications: ['identity', 'tax', 'expert'],
        serviceAreas: ['Baramati', 'Pune', 'Solapur'],
        repeatCustomers: 28,
        verifiedBookings: 42,
        onTimeRate: 96,
      },
      reviews: [
        {
          id: 'rv-a1',
          author: 'Co-op Member',
          rating: 5,
          text: 'Even coverage and professional pilot. Saved us days of manual work.',
          date: 'Jan 20, 2026',
          verified: true,
        },
      ],
    },
    {
      id: 'A-402',
      title: 'Crop Imaging Survey',
      subtitle: 'NDVI mapping',
      provider: 'AeroScan India',
      rate: 2800,
      unit: 'plot',
      durationMinutes: 60,
      status: 'booked',
      location: 'Solapur',
      rating: 4.6,
      reviewCount: 20,
      description: 'Aerial crop health mapping with NDVI analysis.',
      includes: ['Survey flight', 'NDVI report', 'Hotspot map'],
      nextAvailable: ['Sep 6'],
      createdAt: '2025-05-10',
      bookingCount: 35,
      cancellationPolicy: 'Reschedule if weather prevents flight.',
      format: 'Aerial survey + report',
      providerProfile: {
        title: 'Aerial Imaging Specialist',
        experienceYears: 5,
        responseTime: '1 day',
        responseRate: 95,
        acceptanceRate: 93,
        specializations: ['NDVI mapping', 'Crop scouting'],
        certifications: ['Remote Sensing Certified'],
        verifications: ['identity', 'email', 'expert'],
        serviceAreas: ['Solapur', 'Baramati'],
        repeatCustomers: 11,
        verifiedBookings: 20,
        onTimeRate: 94,
      },
      reviews: [],
    },
  ],
  irrigation: [
    {
      id: 'I-501',
      title: 'Drip Layout Setup',
      subtitle: 'Design + install',
      provider: 'HydroGrow Systems',
      rate: 9000,
      unit: 'plot',
      durationMinutes: 240,
      status: 'open',
      location: 'Bangalore',
      rating: 4.8,
      reviewCount: 27,
      description: 'End-to-end drip irrigation design and installation.',
      includes: ['Site survey', 'Layout design', 'Installation'],
      nextAvailable: ['Sep 4', 'Sep 10'],
      createdAt: '2025-07-01',
      bookingCount: 38,
      cancellationPolicy: 'Deposit refundable if cancelled before site survey.',
      format: 'On-site installation',
      providerProfile: {
        title: 'Irrigation Engineer',
        experienceYears: 9,
        responseTime: '1 day',
        responseRate: 96,
        acceptanceRate: 94,
        specializations: ['Drip irrigation', 'System design'],
        certifications: ['Irrigation Association Certified'],
        verifications: ['identity', 'phone', 'tax', 'expert'],
        serviceAreas: ['Bangalore', 'Mysuru'],
        repeatCustomers: 14,
        verifiedBookings: 27,
        onTimeRate: 97,
      },
      reviews: [
        {
          id: 'rv-i1',
          author: 'Organic Farm Owner',
          rating: 5,
          text: 'Professional layout and clean installation.',
          date: 'Dec 15, 2025',
          verified: true,
        },
      ],
    },
    {
      id: 'I-502',
      title: 'Pump Installation',
      subtitle: 'Submersible systems',
      provider: 'AquaTech Installers',
      rate: 15000,
      unit: 'unit',
      durationMinutes: 300,
      status: 'open',
      location: 'Mysuru',
      rating: 4.5,
      reviewCount: 14,
      description: 'Professional submersible pump installation and commissioning.',
      includes: ['Pump setup', 'Electrical hookup', 'Warranty registration'],
      nextAvailable: ['Aug 30', 'Sep 7'],
      createdAt: '2025-06-01',
      bookingCount: 19,
      cancellationPolicy: 'Cancel before materials ordered for full refund.',
      format: 'On-site installation',
      providerProfile: {
        title: 'Pump Installation Specialist',
        experienceYears: 11,
        responseTime: '2 days',
        responseRate: 93,
        acceptanceRate: 91,
        specializations: ['Pump installation', 'Electrical'],
        certifications: ['Licensed Electrician Partner'],
        verifications: ['identity', 'tax'],
        serviceAreas: ['Mysuru', 'Bangalore'],
        repeatCustomers: 7,
        verifiedBookings: 14,
        onTimeRate: 92,
      },
      reviews: [],
    },
  ],
}

export function statusBadge(status: ServiceStatus): 'active' | 'accepted' | 'pending' {
  if (status === 'open') return 'active'
  if (status === 'booked') return 'accepted'
  return 'pending'
}

export function statusLabel(status: ServiceStatus): string {
  if (status === 'open') return 'Open for booking'
  if (status === 'booked') return 'Fully booked'
  return 'Paused'
}

export function verificationLabel(v: string): string {
  const map: Record<string, string> = {
    identity: 'Identity verified',
    email: 'Email verified',
    phone: 'Phone verified',
    tax: 'Tax ID verified',
    expert: 'Expert certification verified',
  }
  return map[v] ?? v
}
